name: NPM Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$BUN_INSTALL/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm install -g node-gyp
          bun install

      - name: Build & Set Package Version to Tag
        run: |
          bun run build
          VERSION=${GITHUB_REF#refs/tags/}
          npm version $VERSION --no-git-tag-version

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
